config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:index]

  resources :relationships, only: [:show, :create, :destroy]

  resources :poems, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<h2>お知らせ</h2>
<% if @notifications.count == 0 %>
  <h3>新着の通知は現在ありません</h3>
<% end %>
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
  <ul class="list-group">
    <% @notifications.each do |notification| %>
      <li class="list-group-item">
        <% if notification.read == true %>
          <span class="left"><strong>[既読]</strong></span>
        <% else %>
          <span class="left"><strong>[未読]</strong></span>
        <% end %>
        <%= notification.comment.user.try(:name) %>さんが
        あなたのブログ(<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>)にコメントしました。
        (<%= notification.created_at %>)
      </li>
    <% end %>
  </ul>
</div>